# uri base
@uri = http://localhost:{{$dotenv PORT}}

## connexion user avec droit en lecture
POST {{uri}}/api/users/login
Content-Type: application/json

{
    "email":"aviateur22@msn.com",
    "password":"aaaa"
}

### connexion user avec droit en écriture
POST {{uri}}/api/users/login
Content-Type: application/json

{
    "email":"aviateur22@hotmail.fr",
    "password":"aaaa"
}

### connexion user avec droit admin
POST {{uri}}/api/users/login
Content-Type: application/json

{
    "email":"aviateur22@gmail.com",
    "password":"aaaa"
}

### token pour requete
@jwtToken = authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInJvbGUiOjMsImlhdCI6MTY0OTc2OTA1NSwiZXhwIjoxNjQ5NzcwODU1LCJpc3MiOiJiYWNrLWF1dGgtbXlMZXNzb24iLCJzdWIiOiJhdXRob3JpemF0aW9uIiwianRpIjoiNDVlMDRjMGMtYmI0NS00MWY5LWE4MTgtZDQ3MGJiM2Y5ZTViIn0.LbtlpWp4Ul6tK7D4PJb6_hhiVycMgozt10Fvn_cUIf4

### creation d'une lecon
POST {{uri}}/api/lessons
Cookie: {{jwtToken}}
Content-Type: application/json

{
    "title":"fff",
    "content" : "hhhfffffffh",
    "tagId" : "1/2/3",
    "userId" : "2",
    "summary" : "ddddd",
    "thematicId": 1,
    "formToken": "ffggggf"
}

### modification d'une lecon par son id
PATCH  {{uri}}/api/lessons/2
Cookie: {{jwtToken}}
Content-Type: application/json

{
    "title":"hel",
    "content" : "boum badamboum",
    "tagId" : "1/2/3",
    "userId" : "2"
}

### Récuperation leçon par son id
POST  {{uri}}/api/lessons/1
Content-Type: application/json

{
    "userId" : "2"
}

### suppression d'une lecon par son id
DELETE {{uri}}/api/lessons/5
Cookie: {{jwtToken}}
Content-Type: application/json

{
   "userId" :"2"
}

### Recuperation all lesson
GET {{uri}}/api/lessons
Cookie: {{jwtToken}}


### Recuperation lecon par tag
POST {{uri}}/api/lessons/filter/tags
Cookie: {{jwtToken}}
Content-Type: application/json

{
   "tags" :[2, 10]
}

### Recuperation de toutes les lecon par userid
GET  {{uri}}/api/lessons/user/2
Cookie: {{jwtToken}}
Content-Type: application/json

{

}

### suppression d'une lecon par son id
DELETE   {{uri}}/api/lessons/6
Cookie: {{jwtToken}}
Content-Type: application/json

{
    "userId": 2,
    "formToken" : "s"
}

### récuperation lecon par son slug
GET {{uri}}/api/lessons/slug/dss
Cookie: {{jwtToken}}
Content-Type: application/json

{

}
