# uribase
@uri = http://localhost:{{$dotenv PORT}}

### inscription
POST {{uri}}/api/users
Content-Type: application/json

{
    "login":"aaa",
    "email":"aaa@gmail.com",
    "password":"Affirmer2011@",
    "confirmPassword":"Affirmer2011@"
}

### connexion user avec droit en lecture
POST {{uri}}/api/users/login
Content-Type: application/json

{
    "email":"aaa@gmail.com",
    "password":"Affirmer2010@"
}

### connexion user avec droit en écriture
POST {{uri}}/api/users/login
Content-Type: application/json

{
    "email":"aviateur22@hotmail.fr",
    "password":"aaaa"
}

### connexion user avec droit admin
POST {{uri}}/api/users/login
Content-Type: application/json

{
    "email":"aviateur22@gmail.com",
    "password":"aaaa"
}

### token pour requete
@jwtToken = authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInJvbGUiOjMsImlhdCI6MTY0ODg5NjE0MSwiZXhwIjoxNjQ4ODk3OTQxLCJpc3MiOiJiYWNrLWF1dGgtbXlMZXNzb24iLCJzdWIiOiJhdXRob3JpemF0aW9uIiwianRpIjoiYWQ5YjZhYTctNjdlOC00ZjU5LWE1OGUtODViODQ0MWVlYWU5In0.Bi4HpyD3cJkDRPklW4i7rTgfNFIfYED7641pNd0qKQs

### ajout d'un link utilisateur
POST {{uri}}/api/links/user/1
Cookie: {{jwtToken}}
Content-Type: application/json

{
    "linkUrl": "https://github.com/sssgg",
    "mediaId": "1"
}

### récuperation de tous les link d'un utilisateur
GET  {{uri}}/api/links/user/1
Cookie: {{jwtToken}}
Content-Type: application/json

{
    
}

### récuperation de tous les link disponible
GET  {{uri}}/api/links/
Cookie: {{jwtToken}}
Content-Type: application/json

{
    
}
