# uribase
@uri = http://localhost:{{$dotenv PORT}}

### inscription
POST {{uri}}/api/users
Content-Type: application/json

{
    "login":"aaa",
    "email":"aaa@gmail.com",
    "password":"Affirmer2011@",
    "confirmPassword":"Affirmer2011@"
}

### connexion user avec droit en lecture
POST {{uri}}/api/users/login
Content-Type: application/json

{
    "email":"aaa@gmail.com",
    "password":"Affirmer2011@"
}

### connexion user avec droit en écriture
POST {{uri}}/api/users/login
Content-Type: application/json

{
    "email":"aviateur22@hotmail.fr",
    "password":"aaaa"
}

### connexion user avec droit admin
POST {{uri}}/api/users/login
Content-Type: application/json

{
    "email":"aviateur22@gmail.com",
    "password":"aaaa"
}

### token pour requete
@jwtToken =  authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOjIsImlhdCI6MTY1MjYwMTM3NSwiZXhwIjoxNjUyNjAzMTc1LCJpc3MiOiJiYWNrLWF1dGgtbXlMZXNzb24iLCJzdWIiOiJhdXRob3JpemF0aW9uIiwianRpIjoiMGZmYmRjOWItODc3ZS00MTlmLThkNjItMGMwZmRjOGIwYTQ3In0.e4mkS1JsrJrJkkVayAHBfeJ1zjP6oJP6Sn6Op9KBgLs


### suppression notif
DELETE  {{uri}}/api/notifications/4
Cookie: {{jwtToken}}
Content-Type: application/json

{
    "userId": 2    
}

### liste  de tous les notifi de 1 utilisateur
GET {{uri}}/api/notifications/notification-by-user/2
Cookie: {{jwtToken}}
Content-Type: application/json

{
 
}

### count notification
GET {{uri}}/api/notifications/notification-by-user/count/2
Cookie: {{jwtToken}}
Content-Type: application/json

{

}

### lecture notification
PATCH  {{uri}}/api/notifications/read/1
Cookie: {{jwtToken}}
Content-Type: application/json

{
    "userId": 150
}