# uribase
@uri = http://localhost:{{$dotenv PORT}}

### inscription
POST {{uri}}/api/users
Content-Type: application/json

{
    "login":"aaa",
    "email":"asaa@gmail.com",
    "password":"Affirmer2011@",
    "confirmPassword":"Affirmer2011@"
}

### connexion user avec droit en lecture
POST {{uri}}/api/users/login
Content-Type: application/json

{
    "email":"aaa@gmail.com",
    "password":"Affirmer2011@"
}

### connexion user avec droit en écriture
POST {{uri}}/api/users/login
Content-Type: application/json

{
    "email":"aviateur22@hotmail.fr",
    "password":"aaaa"
}

### connexion user avec droit admin
POST {{uri}}/api/users/login
Content-Type: application/json

{
    "email":"aviateur22@gmail.com",
    "password":"aaaa"
}

### token pour requete
@jwtToken = authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6MywiaWF0IjoxNjQ3ODY5NzYzLCJleHAiOjE2NDc4NzE1NjMsImlzcyI6ImJhY2stYXV0aC1teUxlc3NvbiIsInN1YiI6ImF1dGhvcml6YXRpb24iLCJqdGkiOiI2ZDQ0MDI0OS1lNTgyLTQzOTMtYTJmZS1iOTdlOTA1YjMyYjUifQ.A-ok5LB2G5xiZsf5Un-9RzWPOw88qIPwatfpzi1hEsU


### modification d'utilisateur par son id
PATCH {{uri}}/api/users/5
Cookie: {{jwtToken}}
Content-Type: application/json

{
    "email" : "dfddcsddf@hdhd.com",
    "login" : "fdddF"

}

### suppression d'utilisateur par son id
DELETE {{uri}}/api/users/6
Cookie: {{jwtToken}}
Content-Type: application/json

{
    
}

### récupération d'utilisateur par son id
GET  {{uri}}/api/users/8
Cookie: {{jwtToken}}
Content-Type: application/json

{
    
}

### modification mot de passe
PATCH   {{uri}}/api/users/password/7
Cookie: {{jwtToken}}
Content-Type: application/json

{
    "password" : "Affirmer2010@",
    "newPassword" : "Affirmer2010@",
    "confirmNewPassword" : "Affirmer2010@"     
}

### récuperation de tous les utilisateurs
GET  {{uri}}/api/users
Cookie: {{jwtToken}}
Content-Type: application/json

{

}

### logout utilisateur
POST {{uri}}/api/users/logout
Content-Type: application/json

{

}
