# uri base
@uri = http://localhost:{{$dotenv PORT}}

## connexion user avec droit en lecture
POST {{uri}}/api/users/login
Content-Type: application/json

{
    "email":"aviateur22@msn.com",
    "password":"aaaa"
}

### connexion user avec droit en écriture
POST {{uri}}/api/users/login
Content-Type: application/json

{
    "email":"aviateur22@hotmail.fr",
    "password":"aaaa"
}

### connexion user avec droit admin
POST {{uri}}/api/users/login
Content-Type: application/json

{
    "email":"aviateur22@gmail.com",
    "password":"aaaa"
}

### token pour requete
@jwtToken = authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6MywiaWF0IjoxNjQ3ODk5MTM5LCJleHAiOjE2NDc5MDA5MzksImlzcyI6ImJhY2stYXV0aC1teUxlc3NvbiIsInN1YiI6ImF1dGhvcml6YXRpb24iLCJqdGkiOiIwZjVjZDlmNy05ZTNiLTQyOGEtYTVlYy03ZDdkMmQyMDA0ZTYifQ.71Bj5TxSCoENs9QcPHlGgd03eZlGaSdMN5MHNTfXEJY

### creation d'un tag
POST  {{uri}}/api/tags
Cookie: {{jwtToken}}
Content-Type: application/json

{
    "name":"fff"
}

### creation d'un tag
POST  {{uri}}/api/tags
Cookie: {{jwtToken}}
Content-Type: application/json

{
    "name":"fff"
}


### suppression d'un tag
DELETE  {{uri}}/api/tags/21
Cookie: {{jwtToken}}

###  récupération tag byId
GET {{uri}}/api/tags/16
Cookie: {{jwtToken}}

###  récupération tag byId
GET {{uri}}/api/tags/name/b
Cookie: {{jwtToken}}

###  récupération de tous les tags
GET {{uri}}/api/tags
Cookie: {{jwtToken}}

### update d'un tag byid
PATCH   {{uri}}/api/tags/20
Cookie: {{jwtToken}}
Content-Type: application/json

{
    "name":"fff"
}


