-- Deploy mylesson:notification to pg

BEGIN;

CREATE TABLE "notification"(
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "text" TEXT NOT NULL,
    "new" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "user_has_notification"(
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    
    "user_id" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "notification_id" INTEGER NOT NULL REFERENCES "notification"("id") ON DELETE CASCADE,
    "user_source_id" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,    
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ
);

COMMIT;
